[profile.default]
src = "src"
out = "out"
libs = ["lib"]

gas_reports = ["*"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_MAINNET_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
anvil = "http://localhost:8545"
polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_POLYGON_API_KEY}"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_ARBITRUM_API_KEY}"
arbitrum_official = "https://arb1.arbitrum.io/rpc"
optimism = "https://opt-mainnet.g.alchemy.com/v2/${ALCHEMY_MAINNET_API_KEY}"
base = "https://radial-alien-bush.base-mainnet.quiknode.pro/${QUICKNODE_BASE_API_KEY}/"
mantle = "https://rpc.mantle.xyz/"
scroll = "https://rpc.scroll.io/"

[etherscan]
mainnet = { key = "${MAIN_ETHERSCAN_API_KEY}" }
sepolia = { key = "${MAIN_ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
optimism = { key = "${OPT_ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }